name: Copy latest release

on: release

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Copy latest release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "master"
      - run: |
          tagName=$(gh release list --exclude-pre-releases --exclude-drafts --json tagName,isLatest -q '.[] | select(.isLatest == true) | .tagName')
          if [[ -z $tagName ]]; then
            echo "::error::Failed to find latest release"
            exit 1
          fi
          gh release view $tagName > LATEST-RELEASE.md
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[skip ci] save latest release notes"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
